### PR TITLE
refactored

### PR DESCRIPTION
**Pull request by T1G37**

### CODE REVIEW

**Comment by ZeNyfh** [comment]
7b46a1d looks good, checking if 68cd2aa is fine now.

**Comment by ZeNyfh** [comment]
@9382 when you are available, could you check if this is fine, I *think* its alright, ive checked that the removal of redundant options is fine but I just need to see if you agree with that.

**Comment by 9382** [comment]
Since I've received multiple messages asking about this PR, I'll clarify
I'm unable to participate for at least the next 5h, so please be patient

**Review by 9382 — APPROVED** [review]
The split technically causes issue if the user invokes the command using a ping and a newline to split "bug" and the args (yes this is legal behaviour), but this isn't important enough for me to justify rejecting this

**Pull request merged**
